added profile and home page,UserController
xerxes-on/pet_Project_main pull request #1
Opened 2024-07-31 11:04 UTC by xerxes-on

2024-08-07 08:27 UTC, YauheniNikifarau requested changes

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Http/Controllers/Api/BookController.php
> +         return response(BooksResource::collection($books), $count);
Second argument of response() helper should be response code

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Http/Controllers/Api/QuoteController.php
> +        return response($result, 401);
why 401?

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Http/Controllers/Api/QuoteController.php
> +        $result = Quote::create($request->all());
passing $request->all() to create method is not the best practise. There is DTO recommended to be used.

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Http/Controllers/Api/QuoteController.php
> +            return ('There is no hotel with such id');
Seems wrong. 'response' missing

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Http/Controllers/Api/QuoteController.php
> +        $quote->update($request->all());
See below about $response->all()

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Http/Controllers/Api/QuoteController.php
> +            return response('deleted', 200);
code 200 is less suitable here, other code is more suitable

2024-08-07 08:27 UTC, YauheniNikifarau commented on app/Models/Rating.php
>      public function user()
Bette to add Response type here

2024-08-09 08:34 UTC, xerxes-on commented on app/Http/Controllers/Api/QuoteController.php
> +        return response($result, 401);
it should be 200( success) my mistake

2024-08-09 08:41 UTC, xerxes-on commented on app/Models/Rating.php
>      public function user()
what about $guarded = []; ?

2024-08-09 08:42 UTC, xerxes-on commented on app/Http/Controllers/Api/QuoteController.php
> +            return response('deleted', 200);
Ok

2024-08-09 08:45 UTC, merged